services:

    UserBundle:
        registration_listener:
            class: UserBundle\EventListener\RegistrationListener
            arguments: []
            tags:
                - { name: kernel.event_subscriber}