<?php
/**
 * Created by PhpStorm.
 * User: Fabrice
 * Date: 13/07/2017
 * Time: 00:54
 */

namespace UserBundle\Form;


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use UserBundle\EventListener\RegistrationListener;


class RegistrationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->add('name',null,array('label' => 'form.name', 'translation_domain' => 'UserBundle'))
            ->add('firstname',null,array('label' => 'form.firstname', 'translation_domain' => 'UserBundle'))
        ->add('cgu', CheckboxType::class, array(
            'label'     => 'Je reconnais…',
            'required'  => true,
            'mapped' => false
        ));
        $builder->addEventSubscriber(new RegistrationListener());

    }

    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';
    }

    public function getBlockPrefix()
    {
        return 'app_user_registration';
    }
}